### PR TITLE
Authentication tests added

### PR DESCRIPTION
**Pull request by heet-2312**
test

### CODE REVIEW

**Comment by heet-2312** [comment]
#8

**Comment by heet-2312** [comment]
Please merge this pull request i have added test for authentication routes #8

**Comment by sarthakkundra** [comment]
@heet-2312 75 points

**Comment by sarthakkundra** [comment]
@heet-2312 Great work! 👍

**Comment by meet59patel** [comment]
> @heet-2312 75 points

@sarthakkundra This is incorrect comment format so it was ignored, please make another comment `give @heet-2312 75 points`

**Pull request merged**
